name: Pack and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: â• Add nugets source
      uses: unosquare/add-nuget-source@master 
      with:
        access-token: ${{ secrets.GPR_ACCESS_TOKEN }}
        org: 'mariodivece'
    - name: ğŸ Bump version
      uses: unosquare/bump-nuget-version@master 
      with:
        level: ${{ contains(github.event.head_commit.message, '[PATCH]') && 'patch' || 'prerelease' }}
        csproj: /home/runner/work/blazorific/blazorific/Unosquare.Blazorific/Unosquare.Blazorific.csproj
    - name: ğŸ— Build and pack nuget
      run: |
        dotnet build -c Release
        dotnet pack --configuration Release
    - name: ğŸ± Publish nuget
      uses: unosquare/publish-nuget-package@master 
      with:
        access-token: ${{secrets.GPR_ACCESS_TOKEN}}
        path: /home/runner/work/blazorific/blazorific/Unosquare.Blazorific/bin/Release
    - name: ğŸ“Œ Commit
      uses: EndBug/add-and-commit@v4
      with:
        author_name: '@mariodivece'
        author_email: 'mariodivece@users.noreply.github.com'
      env:
        GITHUB_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN }}
        
